### PR TITLE
Changed date format in download email.

### PR DESCRIPTION
**Pull request by alexhuang091**
As per request https://github.com/AtlasOfLivingAustralia/DataQuality/issues/129, changed the date format in the email.

Nick has no problem with it.

### CODE REVIEW

**Comment by ansell** [comment]
I agree with the change for Australian users at least who are familiar with that particular date format.

However, the change being done here will not directly influence any of our other test or production systems as this file is not directly used for any configuration other than for developer systems. We need to change this configuration item in our ansible inventory files rather than here to push this change through to test/production.

**Comment by alexhuang091** [comment]
> I agree with the change for Australian users at least who are familiar with that particular date format.
> 
> However, the change being done here will not directly influence any of our other test or production systems as this file is not directly used for any configuration other than for developer systems. We need to change this configuration item in our ansible inventory files rather than here to push this change through to test/production.

Thanks Peter. I didn't test on my machine, but shouldn't this file be copied to /data/config as long as you have `biocache-properties` role defined?

**Comment by ansell** [comment]
@alexhuang091 This file has no use outside of development machines as far as I know. You will need to change the ansible config file in `ala-install` to practically change the default after discussing whether the default should be changed for all Living Atlases with @vjrj :

https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/roles/biocache-properties/templates/biocache-config.properties

If we are leaving the default as it is currently to suit other Living Atlases, then this change would be done in our private ansible inventory files

**Comment by alexhuang091** [comment]
> @alexhuang091 This file has no use outside of development machines as far as I know. You will need to change the ansible config file in `ala-install` to practically change the default after discussing whether the default should be changed for all Living Atlases with @vjrj :
> 
> https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/roles/biocache-properties/templates/biocache-config.properties
> 
> If we are leaving the default as it is currently to suit other Living Atlases, then this change would be done in our private ansible inventory files

Thanks Peter, you are correct. The script in `ala-install/ansible/roles/biocache-properties/tasks/main.yml`

_- name: copy biocache config properties template
  template: src={{item}} dest={{data_dir}}/biocache/config/{{item}} mode=0644 output_encoding=iso-8859-1
  with_items:
    - biocache-config.properties
  tags:
    - properties
    - biocache-properties_

should mean to copy `biocache-config.properties` from template folder instead of source code folder to data folder.

I'll check how to update it.

**Comment by alexhuang091** [comment]
Hi Peter, https://github.com/AtlasOfLivingAustralia/biocache-service/pull/510 is created for this.

I've changed the default date format in the source code. This way if any environment wants a different date format they can set it in the external config file to overwrite it. (Currently no ansible script writes this value so the default value in source code will be used).

This PR will be closed.

**Pull request closed without merging**
