### PR TITLE
Added CaseInsensitiveFilter for WMS tile requests

### LINKED ISSUE #366: OGC service params should be case insensitive
Currently some OGC services (e.g. WMS tiles) require the OGC params to be provided in upper case. The problem is that recent versions of Leaflet send the various dynamic params in lower case by default and the tiles fail to load. There is an option in Leaflet to send params in upper case (`uppercase: true`) but this sends all params in upper case and then the ALA-defined params are ignored. E.g. `LAT` and `LON` are ignored, as they are required to sent in lowercase! 

The OGC spec says params should not be case sensitive:

http://cite.opengeospatial.org/OGCTestData/wms/1.1.1/spec/wms1.1.1.html#basic_elements.param_rules.order_and_case

### PR DESCRIPTION
**Pull request by KeyboardSounds**
Fixes #366.

All parameters requests to urls matching `/ogc/*` will be treated as case insensitive.

### CODE REVIEW

**Comment by KeyboardSounds** [comment]
@djtfmartin I haven't been able to test this yet, because I can't write to the /data folder on my computer (which I imagine is the case for most Mac users). Short of setting up a VM, and then trying to run the SOLR and Cassandra docker containers inside that, is there another way to run this locally?

**Comment by djtfmartin** [comment]
thanks @KeyboardSounds - I believe you can do this with `/etc/synthetic.conf` - but i haven't tried it myself. `man synthetic.conf` has more information.

**Comment by djtfmartin** [comment]
Heres a link provided by a colleague:

https://derflounder.wordpress.com/2020/01/18/creating-root-level-directories-and-symbolic-links-on-macos-catalina/

**Comment by KeyboardSounds** [comment]
@djtfmartin worked like a charm! I've done some minimal testing but I'm not really familiar enough with the platform as a whole to do substantial integration testing. If you or someone else could have a closer look and make sure I haven't broken anything by accident, that would be great.

**Comment by brucehyslop** [comment]
This is an interesting solution to this issue.

I've confirmed that the request parameter value is handled independently of its case. 

@KeyboardSounds could you please change the merge destination to `AtlasOfLivingAustralia:develop`

**Comment by brucehyslop** [comment]
QAed on test environment.

Positive test:
`https://biocache-test.ala.org.au/ws/ogc/wms/reflect?q=Macropus+rufus&bbox=-180,-90,180,90`
returns HTTP 200 with image/png

Negative test on prod:
`https://biocache-ws.ala.org.au/ws/ogc/wms/reflect?q=Macropus+rufus&bbox=-180,-90,180,90`
returns HTTP 400
```
Missing valid BBOX parameter
```

**Pull request merged**
