### PR TITLE
issue #405 : CSDM custom templates

### PR DESCRIPTION
**Pull request by ansell**
This is a pull request to review the changes for CSDM to add custom email templates.

### CODE REVIEW

**Comment by ansell** [comment]
Closing this in favour of #444

**Comment by ansell** [comment]
@temi It is unacceptable that you merged this without fixing the issues highlighted in #444 We need to have an ALA wide discussion about what Peer Review means in the future to avoid these issues. I am reverting the merge commit and handing this over to @nickdos for further investigation about the causes behind this.

**Comment by temi** [comment]
@ansell I had conversation a with @nickdos . He was satisfied since Dave had reviewed it. And no commits were added after his approval. So doing another review is pointless. Hence the merge.

The confusion arose because I thought the code was not review and hence asked you to do it. Later, I realised that you had created a PR for it (#411) and @djtfmartin had review it.

**Comment by nickdos** [comment]
@djtfmartin did approve the code review but I'll follow up with him on the points raised by @ansell as he may not have noticed them.

**Pull request merged**
